settings:
  title: 'Status Page'
  url: 'https://status.supunsathsara.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: supunsathsara-com # unique identifier
    name: supunsathsara.com
    description: 'Personal Website.' # default=empty
    url: 'https://supunsathsara.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: bio-supunsathsara-com
    name: bio.supunsathsara.com
    description: 'Contact Details.'
    url: 'https://bio.supunsathsara.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: supunsathsara.github.io
    url: 'https://supunsathsara.github.io'
    method: GET
    expectStatus: 200
    linkable: true
