settings:
  title: 'Status Page'
  url: 'https://status.zim.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  gravatar_email: 'miles@zim.dev'
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: api-zim-dev # unique identifier
    name: api.zim.dev
#     description: 'api.zim.dev' # default=empty
    url: 'https://api.zim.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: zim-dev
    name: zim.dev
#     description: 'zim.dev'
    url: 'https://zim.dev'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: driftdb-zim-dev
    name: driftdb.zim.dev
    url: 'https://driftdb.zim.dev/'
    method: GET
    expectStatus: 200
    linkable: false
